CREATE TABLE "simulations" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "amount" double precision NOT NULL,
    "interest" double precision NOT NULL,
    "periods" double precision NOT NULL,
    "monthly_payment" double precision NOT NULL,
    "created_at" timestamptz NOT NULL,
    PRIMARY KEY ("id")
);